name: Build and local test

on:
  push:
    branches: [ "develop", "main", "feature/**" ]
  pull_request:
    branches: [ "develop", "main", "feature/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run gradle tests
        run: ./gradlew test

      - name: Build gradle project
        run: ./gradlew build

#      - name: Build debug
#        run: ./gradlew assembleDebug --stacktrace
#
#      - name: Run local tests
#        run: ./gradlew testDebug --stacktrace
#
#      - name: Upload build outputs (APKs)
#        uses: actions/upload-artifact@v3
#        with:
#          name: build-outputs
#          path: ./app/build/outputs
#
#      - name: Upload build reports
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: build-reports
#          path: ./app/build/reports